repos:
  - repo: https://github.com/pycqa/pylint
    rev: v2.12.2
    hooks:
      - id: pylint
        args:
          - --score=n
          - -d missing-module-docstring
          - -d missing-function-docstring
          - -d wrong-import-order
          - -d import-error
          - -d missing-class-docstring
          - -d too-many-arguments
          - -d too-few-public-methods 
        require_serial: false
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.6
    hooks:
      - id: reorder-python-imports
        args: [--py37-plus]
